config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'homes/about'

  resources :events, only: [:new, :create, :index, :show, :destroy, :edit, :update]

  resources :users, only: [:show, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :events, dependent: :destroy


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name,
    presence: true,
    uniqueness: {case_sensitive: false},
    length: {minimum: 2, maximum: 20}

  validates :introduction,
    length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  # サインイン後の遷移先
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  # サインアウト後の遷移先
  def after_sign_out_path_for(resource)
    root_path
  end


  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      flash[:notice] = "投稿が成功しました"
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def index
    @events = Event.page(params[:page]) # ページネーション
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    flash[:notice] = "イベントTODOが削除されました"
    redirect_to user_path(current_user)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.user != current_user
      redirect_to user_path(current_user.id)
      return
    end

    if @event.update(event_params)
      flash[:notice] = "編集内容が反映されました"
      redirect_to event_path(@event.id)
    else
      render :edit
    end
  end


  private

  # ストロングパラメータ
  def event_params
    params.require(:event).permit(:name, :introduction, :genre, :start_at, :end_at)
  end

  # TODO編集画面へのアクセス制御
  def is_matching_login_user
    user = Event.find(params[:id]).user
    unless user.id == current_user.id
      redirect_to events_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @events = @user.events.page(params[:page]) # ページネーション
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user != current_user
      redirect_to user_path(current_user.id)
      return
    end

    if @user.update(user_params)
      flash[:notice] = "プロフィールの保存が完了しました"
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end


  private

  # ストロングパラメータ
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  # ユーザプロフィールへのアクセス制御
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: event do |f| %>
  <div class="mb-3">
    <h5><i class="far fa-flag"></i> イベント名</h5>
    <%= f.text_field :name, autofocus: true, class:"form-control", placeholder:"イベント名" %>
  </div>

  <div class="mb-3">
    <h5><i class="fa-solid fa-pen-fancy"></i> イベント詳細</h5>
    <%= f.text_area :introduction, autofocus: true %>
  </div>

  <div class="mb-3">
    <h5><i class="fa-solid fa-tag"></i> イベントのジャンル</h5>
    <%= f.select :genre, {'音楽':'音楽', '小説':'小説', '漫画':'漫画', 'イラスト':'イラスト', 'ものつくり':'ものつくり', 'その他':'その他'}, { include_blank: '選択してください'} %>
  </div>

  <div class="mb-3">
    <h5><i class="fa-regular fa-clock"></i> イベント開始日時</h5>
    <%= f.date_field :start_at %>
  </div>

  <div class="mb-3">
    <h5><i class="fa-solid fa-clock"></i> イベント終了日時</h5>
    <%= f.date_field :end_at %>
  </div>

  <%= f.submit "送信", class:"btn btn-lg btn-block btn-info mt-4" %>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <div class="text-dark bg-light p-4 mb-0">
        <div class="text-right">
          <%= link_to event_path(@event), class:"btn btn-outline-secondary btn-sm mb-2" do %>
            <i class="fa-solid fa-arrow-left"></i> 戻る
          <% end %>
        </div>
        <h5 class="text-center"><i class="fa-solid fa-gear"></i> イベントTODO編集</h5>
      </div>
      <div class="form-body p-4">
        <!--バリデーションエラー部-->
        <%= render "templates/validation", obj: @event %>
        <!--投稿フォーム部-->
        <%= render "form", event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h4 class="p-3 border-bottom">みんなのイベントTODO</h4>
    </div>
  </div>
</div>

<%= render 'templates/index', events: @events %>

app/views/events/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <div class="text-dark bg-light p-4 mb-0">
        <div class="text-right">
          <%= link_to user_path(current_user), class:"btn btn-outline-secondary btn-sm mb-2" do %>
            <i class="fa-solid fa-arrow-left"></i> 戻る
          <% end %>
        </div>
        <h5 class="text-center"><i class="fa-solid fa-plus"></i> イベントTODO投稿</h5>
      </div>
      <div class="form-body p-4">
        <!--バリデーションエラー部-->
        <%= render "templates/validation", obj: @event %>
        <!--投稿フォーム部-->
        <%= render "form", event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <h4 class="p-3 border-bottom text-center">イベントTODO詳細</h4>
  <div class="row mt-5 mb-5">
    <div class="col-4">
      <div class="pt-4 pl-5">
        <h6><i class="fa-solid fa-user"></i> 投稿ユーザー</h6>
        <%= link_to(user_path(@event.user), class:"text-dark") do %>
          <%= image_tag @event.user.get_profile_image(150,150), class:"mt-3"; %>
          <p class="h5"><%= @event.user.name %></p>
        <% end %>
      </div>
    </div>

    <div class="col-8">
      <div class="p-3 w-75">
        <h6 class="border-bottom"><i class="far fa-flag"></i> イベント名:</h6>
        <p class="h5"><%= @event.name %></p>
      </div>

      <div class="p-3 w-75">
        <h6 class="border-bottom"><i class="fa-regular fa-clock"></i> イベント開催日程:</h6>
        <p class="h5"><%= @event.start_at %> ~ <%= @event.end_at %></p>
      </div>

      <div class="p-3 w-75">
        <h6 class="border-bottom"><i class="fa-solid fa-pen-fancy"></i> イベント詳細:</h6>
        <p class="h5"><%= @event.introduction %></p>
      </div>

      <div class="p-3 w-75">
        <h6 class="border-bottom"><i class="fa-solid fa-tag"></i> ジャンル:</h6>
        <p class="h5"><%= @event.genre %></p>
      </div>

        <div class="p-3 w-75 text-right">
          <% if @event.user == current_user %>
            <%= link_to "編集", edit_event_path(@event), class:"btn btn-secondary mr-3" %>
            <%= link_to "削除", event_path(@event), class:"btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
          <% end %>
        </div>
    </div>

  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6 text-center">
      <i class="fa-regular fa-calendar fa-4x mb-4"></i>
      <h1 style="font-family: cursive;" class="mb-5 border-bottom">About Page</h1>
      
      <p style="font-family: serif;">Eventareは「Event」を「Share」するためのアプリです.</p>
      <p style="font-family: serif;">主に音楽や執筆などの創作活動を行っている方に向けています.</p>
      <p style="font-family: serif;">
        創作イベントなどに応募することを忘れないためのTODO作成や,<br>
        自分が知らない, 他の創作者が知っているイベントを把握するために便利です.
      </p>

    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6 text-center">
      <i class="fa-regular fa-calendar fa-4x mb-4"></i>
      <h1 style="font-family: cursive;" class="mb-5 border-bottom">Eventare</h1>

      <p style="font-family: serif;">イベントやコンテストをTODOとして投稿したり</p>
      <p style="font-family: serif;">他の人が投稿したTODOからまだ見ぬイベントやコンテストを知ることができます</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row mt-4">
          <%= link_to new_user_session_path, class:"btn btn-success btn-block mb-3" do %>
            <i class="fas fa-sign-in-alt" aria-hidden="true"></i> ログイン
          <% end %>
        </div>
        <div class="row">
          <%= link_to new_user_registration_path, class:"btn btn-info btn-block mb-3" do %>
            <i class="fas fa-user-plus" aria-hidden="true"></i> 新規登録
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/64316cd30c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <div class="fixed-top bg-white">
      <header class="shadow-sm">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <%= link_to root_path, class: 'nav-link text-dark' do %>
              <i class="fa-solid fa-house"></i> Eventare
            <% end %>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to new_event_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-plus" aria-hidden="true"></i> 投稿フォーム
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to events_path, class: 'nav-link text-dark' do %>
                    <i class="fa-solid fa-globe"></i> みんなのTODO
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: 'nav-link text-dark' do %>
                    <i class="fas fa-user" aria-hidden="true"></i> マイページ
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, "data-confirm" => "本当にログアウトしますか？", class: 'nav-link text-dark' do %>
                    <i class="fas fa-sign-out-alt" aria-hidden="true"></i> ログアウト
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to homes_about_path, class: 'nav-link text-dark' do %>
                    <i class="fas fa-link" aria-hidden="true"></i> 概要
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
                    <i class="fas fa-user-plus" aria-hidden="true"></i> 新規登録
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
                    <i class="fas fa-sign-in-alt" aria-hidden="true"></i> ログイン
                  <% end %>
                </li>
              <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    </div>

    <div class="pt-3 pb-5">
      <div class="container mt-5">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-success"><%= message %></div>
        <% end %>
      </div>
      
      <%= yield %>
    </div>

    <div class="fixed-bottom">
      <footer class="mt-5">
        <div class="bg-dark text-white mt-5 pt-4">
          <div class="container">
            <div class="row mx-auto">
              <p>©2023 Eventare</p>
            </div>
          </div>
        </div>
      </footer>
    </div>

  </body>
</html>

app/views/templates/_index.html.erb
<div class="card-list-container py-5">
  <% events.reverse_each do |event| %>
    <div class="card w-50 mx-auto mt-4 shadow-lg">
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <%= link_to(user_path(event.user), class:"text-dark") do %>
              <%= image_tag event.user.get_profile_image(100,100), class:"mt-3 rounded-circle"; %>
              <span><i class="fa-solid fa-user"></i> <%= event.user.name %></span>
            <% end %>
          </div>
          <div class="col-10">
            <%= link_to(event_path(event.id), class:"text-dark") do %>
              <p class="card-title"> <strong><i class="far fa-flag"></i><span> <%= event.name %></span></strong></p>
              <p class="card-text"><i class="fa-solid fa-tag"></i> <%= event.genre %></p>
              <p class="card-text"><i class="fa-regular fa-clock"></i> <%= event.start_at %> ~ <%= event.end_at %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate events %>
</div>

app/views/templates/_validation.html.erb
<% if obj.errors.any? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
      <%= obj.errors.count %>件のエラーが発生しました
    </h6>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <div class="text-dark bg-light p-4 mb-0">
        <div class="text-right">
          <%= link_to user_path(current_user), class:"btn btn-outline-secondary btn-sm mb-2" do %>
            <i class="fa-solid fa-arrow-left"></i> 戻る
          <% end %>
        </div>
        <h5 class="text-center"><i class="fa-solid fa-gear"></i> プロフィール編集</h5>
      </div>
      <div class="form-body p-4">
        <!--バリデーションエラー部-->
        <%= render "templates/validation", obj: @user %>

        <%= form_with model: @user do |f| %>
          <div class="mb-3">
            <h5><i class="fa-solid fa-user"></i> ユーザーネーム</h5>
            <%= f.text_field :name, autofocus: true, placeholder:"名前"%>
          </div>

          <div class="mb-3">
            <h5><i class="fa-solid fa-pen-fancy"></i> 自己紹介</h5>
            <%= f.text_area :introduction, autofocus: true, placeholder:"自己紹介"%>
          </div>

          <div class="mb-3">
            <h5><i class="fa-solid fa-image"></i> プロフィール画像</h5>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          </div>

          <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- ユーザーの詳細 -->
<div class="bg-light mb-3">
  <div class="container mb-3">
    <div class="row">
      <div class="col-2 pt-2 pb-4">
        <%= image_tag @user.get_profile_image(150,150), class:"mt-3 rounded-circle"; %>
      </div>
      <div class="col-10">
        <p class="text-secondary mt-2"><i class="fa-solid fa-list-check"></i> <%= @user.events.count %>件のTODO</p>
        <strong><p class="mt-2 h3"><%= @user.name %></p></strong>
        <p class="pt-3"><%= @user.introduction %></p>
        <% if @user == current_user %>
          <%= link_to "プロフィールを編集", edit_user_path(@user), class:"btn btn-outline-secondary btn-block w-50" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!--投稿一覧-->
<%= render 'templates/index', events: @events %>